enable_logging: true
alternate_ads: true
bossbar_id: "ads"

player_ads_interval:
  min: 15
  max: 60

server_ads_interval:
  min: 30
  max: 60

server_ads:
  - "&aWelcome to our server!"
  - "&eJoin our Discord for rewards!"

muted_players:
  player1: 0

player_ad_format: "§7§o%name%§r: %message%" # Added format option
